version: '3.8'

services:
  php:
    image: php:8.2-apache
    container_name: restaurant2.0
    ports:
      - "8000:80"
    volumes:
      - ./source:/var/www/html
    build: 
      context: .
      dockerfile: DockerFile

  db:
    image: mysql:8.0
    container_name: db-resto
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3307:3306"
  
  phpma:
    image: phpmyadmin/phpmyadmin
    container_name: phpma-resto
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: pass
    ports:
      - 8899:80
